### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [Nephos/todo#2]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by Nephos** [comment]
Still maintained, forgot the v0.26
I'll update those project soon

**Comment by vladfaust** [comment]
Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks.

Please close this issue when updated.

**Comment by Nephos** [comment]
done!
